version: 2.1
jobs:
  build_and_push:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_TAG=${CIRCLE_TAG:-latest}' >> $BASH_ENV
            echo 'export IMAGE_NAME=blog' >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t iwanttobealight/$IMAGE_NAME:$IMAGE_TAG .
            docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
            docker push iwanttobealight/$IMAGE_NAME:$IMAGE_TAG

  deliver:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST "cd /root/iwanttobealight &&
            sudo docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD" &&
            sudo docker pull iwanttobealight/blog &&
            sudo docker logout &&
            sudo docker-compose down &&
            sudo docker-compose up -d &&
            sudo docker image prune -f"


workflows:
  version: 2
  # for master brunch
  deploy-dev:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master
      - deliver:
          filters:
            branches:
              only:
                - master
          requires:
            - build_and_push
          